# Generated by Django 4.1.5 on 2023-01-21 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(null=True)),
                ("job_type", models.CharField(max_length=150, null=True)),
                ("experience_level", models.CharField(max_length=150, null=True)),
                ("medium", models.CharField(max_length=150)),
                ("link", models.URLField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(null=True)),
                ("job_type", models.CharField(max_length=150, null=True)),
                ("experience_level", models.CharField(max_length=150, null=True)),
                ("medium", models.CharField(max_length=150)),
                ("link", models.URLField(max_length=500)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Viewed"),
                            (2, "Contacted"),
                            (3, "Interviewed"),
                            (4, "Accepted"),
                            (5, "Rejected"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
