# Generated by Django 4.1.5 on 2023-01-21 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_application_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="description",
        ),
        migrations.RemoveField(
            model_name="savedjob",
            name="description",
        ),
        migrations.AddField(
            model_name="application",
            name="applied_at",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 1, 21, 10, 40, 24, 184980, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="company",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="posted_at",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 1, 21, 10, 41, 12, 806291, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedjob",
            name="company",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedjob",
            name="posted_at",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 1, 21, 10, 41, 33, 90245, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
