# Generated by Django 4.1.5 on 2023-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_remove_application_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="posted_at",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="savedjob",
            name="posted_at",
            field=models.DateField(null=True),
        ),
    ]
